name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Container start
        run: docker-compose up &
      - name: Waiting for Container start
        run: sleep 60
      - name: Start SUT
        run: java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jbc:mysql://localhost:3306/app &
          # Запускаем SUT,
          # имя файла SUT будет отличаться в каждой задаче.
          # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
          # обязательно должен быть для запуска SUT в CI
      - name: Build with Gradle
        run: ./gradlew test --info "-Dselenide.headless=true"

        # Запускаем автотесты
        # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -Dselenide.headless=true, параметр --info должен остаться

